version: '3.8'

services:
  app:
    build: .
    container_name: sudarshan hotel
    ports:
      - "3000:3000" # Frontend
      - "5000:5000" # Backend
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI} # MongoDB Atlas URI
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID} # Google Auth Client ID
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET} # Google Auth Secret
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET} # NextAuth Secret for Authentication
      PORT: 5000 # Backend port
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
